### PR TITLE
Auto-run MySql tests on both supported providers

### PR DESCRIPTION
**Pull request by mikebeaton**
#311

### CODE REVIEW

**Comment by mikebeaton** [comment]
BOM is byte order mark.

All of the .csproj files in Massive (and in Windows generally) are encoded in UTF-8 with an initial byte order mark (`0xfeff`). I am not quite sure how, but I think as a hang-over from the whitespace problems which I was just looking at, I noticed that I manage to create the Devart `.csproj` file in UTF-8 but without a byte order mark.

I thought it would be nicer (while probably not really affecting anything either way) to take the chance to fix the inconsistency before any merge.

I have squashed everything so that this mistake and fix doesn't need to be in the Massive history.

**Comment by FransBouma** [comment]
ah makes sense and indeed some text files might have a 2-byte preamble that's not correct, I've seen that too in other files, and it's almost always a leftover of editing them in an editor which doesn't support proper BOM values. They go unnoticed most of the time as other editors simply skip the messed up bytes.

**Comment by mikebeaton** [comment]
FWIW I did just check and all my older .csproj files in Windows which have never been touched by Git DO have the two-byte BOM, so I guess that having it is the Windows default (as confirmed by a Google search, too; and vaguely from memory). (I haven't seen an incorrect 2-byte BOM, just present or missing, but I guess that could happen too!)

**Comment by mikebeaton** [comment]
I also checked and every file in this commit is now consistent and consistent with the rest of Massive, i.e. it has the two-byte BOM in every file (only the `.csproj` file was wrong, now fixed).

**Pull request closed without merging**
