### PR TITLE
Remove one unnecessary trailing space

### PR DESCRIPTION
**Pull request by mikebeaton**
Minor change!

### CODE REVIEW

**Comment by FransBouma** [comment]
Come on, man...

**Comment by mikebeaton** [comment]
Okay, misunderstanding. I saw it and thought that (while obviously trivial) it was an edit I'd want made to my own source if I saw it, but that it wouldn't be right to just put it in as part of another change about something completely different? Now not entirely sure what I should have done. Maybe only fix it if it was in or around an area I was working on? Sorry, somewhat new to contributing to open source, apologies if I'm getting some of the etiquette wrong. I guess I'm not taking into account that each pull request is work for yourself, so maybe if it's entirely trivial, it wastes your time, even if it would be worth doing for zero effort - since each pull request is not zero effort.

**Comment by FransBouma** [comment]
The change is trivial, but it's a statistics game. It's nothing personal. I don't know you and there are people out there who make these kind of PRs every day, especially to repositories with a high number of stars so they get high in the committers list or can say they committed a lot of PRs to a given repository, but in reality haven't contributed anything substantial. 

So, changes in whitespace are for me the bottom line, I won't merge them, sorry. Things which make the code better, add features, correct a stupid mistake I made, sure, no problem there. A whitespace correction, however: no, sorry.

**Comment by FransBouma** [comment]
Not to stop you contributing to OSS btw. I know every start is difficult, and where to begin? 

In general to contribute to OSS, use these guidelines: 

- first open an issue and discuss the thing you want to add/change. It might very well be it's not worth it, it has already been discussed/tried and failed/not committed, or it is a tremendous amount of work you don't foresee as you don't know the codebase very well (yet). 
- If the issue discussion is OK, volunteer and say you want to make the change and then make the change, and commit the PR
- When committing the PR, refer to the issue number so things are linked. 
- Always add tests. If you add a generic piece of code to a lib which is used on multiple systems, make sure the generic piece of code works on all those systems. This might be hard in case of Massive as it would require installing Oracle (no-one wants that ;)) or Postgresql and this might take a long time. If that's the case, go back to the issue and mention that so others might add tests after your PR.

**Pull request closed without merging**
