### PR TITLE
Resultset to Datatable

### PR DESCRIPTION
**Pull request by AlphaGeek509**
In response to issue #238.  Credit given to Brian Vallelunga for documenting this in stackflow (http://stackoverflow.com/a/6298704/5262210)

Signed-off-by: Jeff Nichols jnichols@lyntron.com

### CODE REVIEW

**Comment by FransBouma** [comment]
Looks good, (the tabs vs. spaces is easily corrected). I don't know what the licensing terms are of code on SO, so including a piece of code straight from SO is perhaps not a good idea, but I have to check.

**Comment by AlphaGeek509** [comment]
Great point. I never even thought about the terms. I wanted to make sure that I gave the author credit as it was not my work.  That was my intent.  Sorry about the spaces I don't know where that came from. :)

**Comment by FransBouma** [comment]
I saw that, and that's good :) It's just, legally, SO has a ToS for code (which they tend to change soon), I have to look it up for sure. Not that I'm worried, but I like to do things officially. 

Oh don't worry about tabs/spaces. I press cntrl-K-D and things are lined up again as they should ;)

**Comment by FransBouma** [comment]
Looking at this, http://blog.stackoverflow.com/2009/06/attribution-required/ what you did is enough. I'll pull and merge.

**Comment by FransBouma** [comment]
I've moved the test to sqlserver as that's easier for me (oracle is on a separate VM), the test is also not up to par, I've added a better test, which shows a bug in the code: the type of the column isn't set, so it falls back to string. This is crucial, as you want the type of the column to be the same as the original value's type. This is also a problem btw, as the type is unknown if the value is null. The types are known in Query(), if GetSchemaTable is called on the datareader, however the datareader is already closed when the ToDataTable method is called. :/

I'll make it fall back to string if the value is null, and if the value isn't null, use the type of the value for the column. This means that the first row decides the datatable format. I'll also add an overload which accepts a datatable with columns, as that's then a solution for people who have a typed datatable or a setup datatable ready to be filled.

**Pull request merged**
